library(dplyr)
library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
coal_SCC <- SCC %>% filter(grepl("[Cc]oal", EI.Sector)) %>% select(SCC)
q4 <- NEI %>% filter(SCC %in% coal_SCC$SCC) %>% group_by(year) %>% summarise(total_emission = sum(Emissions))
png(filename = "plot4.png", width = 480, height = 480, units = "px")
plot(q4, col = "blue", pch = 19, ylab = "tons", main = "Emssions from Coal Combustion")
dev.off()